name: Deploy to Cloud Run from Source

on: push

env:
  PROJECT_ID: roastmaster
  SERVICE: roastmaster
  REGION: europe-north1

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2.0.0"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }} # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }} # e.g. - my-service-account@my-project.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set DOCKER_TAG
        run: |
          echo "DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push base image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: |
            europe-north1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.PROJECT_ID }}/${{ github.event.repository.name }}:${{ env.DOCKER_TAG }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2.0.0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If required, update to the appropriate source folder
          image: |
            europe-north1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.PROJECT_ID }}/${{ github.event.repository.name }}:${{ env.DOCKER_TAG }}
